# Default configuration for miniboss gate floors
# Floors where a miniboss encounter is required to unlock the stairs.

floors:
  - 20
  - 40
  - 60
  - 80

# The lock reason tag used on stairs. Do not change unless you know all codepaths.
lock_reason: miniboss_gate
