- name: epic
  color: '6f42c1'
  description: High-level initiative tracking multiple issues
- name: epic-child
  color: '1d76db'
  description: Issue created as part of an EPIC
- name: feature
  color: '0e8a16'
  description: New feature
- name: docs
  color: '0075ca'
  description: Documentation
- name: gameplay
  color: 'c2e0c6'
  description: Gameplay systems and balance
- name: systems
  color: 'fef2c0'
  description: Core systems and architecture
