name: Epic
description: Track a multi-task initiative via linked child issues
labels: [epic]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: High-level goal and scope of this epic.
      placeholder: >-
        PyInstaller specs, save locations, CI build.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - Child issues exist and are linked in comments.
        - Labels applied: `epic`.
        - Progress can be tracked via linked issues checklist.
  - type: textarea
    id: children
    attributes:
      label: Children
      description: >-
        Add unchecked checklist items for each child task. Upon creation/edit, a workflow will create issues
        and link them to this epic automatically. You can optionally append "(labels: a,b)" to apply labels.
      value: |
        ### Children
        - [ ] PyInstaller spec & hooks (labels: packaging, build)
        - [ ] Binary icon & metadata (labels: packaging)
        - [ ] Configure save locations and portable mode (labels: platform, save)
        - [ ] CI: Multi-OS build and upload artifacts (labels: ci, build)
        - [ ] Release pipeline: tag -> GitHub Releases assets (labels: release, build)
        - [ ] Smoke test script and preflight validation (labels: qa)
        - [ ] Documentation: packaging and distribution guide (labels: docs)
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Additional context, risks, references.
