name: Manage Epics

on:
  workflow_dispatch:
    inputs:
      config:
        description: Path to epic YAML config
        required: true
        default: configs/epics/dungeon_generation.yml

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyyaml requests
      - name: Apply Epic Spec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python -m am_epic.cli apply -c "${{ github.event.inputs.config }}"
